// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project26.ApplicationDb;

#nullable disable

namespace project26.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425084531_banner-categorytable")]
    partial class bannercategorytable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project26.Models.Banner", b =>
                {
                    b.Property<int>("bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bid"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("bdescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("btitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bid");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("project26.Models.Category", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cid"));

                    b.Property<string>("Imageurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("cid");

                    b.HasIndex("cname")
                        .IsUnique();

                    b.ToTable("Category");
                });

            modelBuilder.Entity("project26.Models.User", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("uid"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("forgotpasscode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("forgotpasstime")
                        .HasColumnType("datetime2");

                    b.Property<string>("uemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("upassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("verifycode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("verifycodetime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("verifystatus")
                        .HasColumnType("bit");

                    b.HasKey("uid");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
